### ISSUE TITLE
Radar last update

### ISSUE THREAD

**Issue by EiTeR94** [Jerry1211/Radar#12]
Hello,

What is that shit "Jerry1211fork" display on the radar lol?
That's so fucking annoying, can we undisplay this please ?
And there is a bug i think, with GRID, this don't work with compass when GRID is activated.

![wtf](https://user-images.githubusercontent.com/20646280/37452106-e6c6a698-2833-11e8-93b6-b5caee5b72d1.png)
![bugs](https://user-images.githubusercontent.com/20646280/37452108-e6dfb2aa-2833-11e8-96f9-bc23be52f37e.png)

**Comment by caoliu1118** [comment]
press insert to hide the menu

**Comment by xXSkrill1337** [comment]
Just press INSERT and calm down xD

**Comment by wuwujia** [comment]
U can choose not to use this while it's public and free.

**Comment by EiTeR94** [comment]
i hit all button on my keyboard, and INSER, doesn't undisplay

**Comment by Mc7qingk** [comment]
Radar is open source and free, you can modify it yourself instead of complaining here

**Comment by Jerry1211** [comment]
i mean i didnt code this for you, GTFO my fork you.

this isnt a RELEASE im just pushing commits so if i happen to fuckup i dont have to redo i can just revert to my last commit.
