### ISSUE TITLE
Function request [enimies info]

### ISSUE THREAD

**Issue by arnanmaipradit** [Jerry1211/Radar#3]
Can u add some
- enemies weapon
- enemies health
- enemies distance
- enemies altitude

**Comment by soulideth** [comment]
cover this https://github.com/XvenDeR/PUBG-Radar-Z

**Comment by arnanmaipradit** [comment]
ty dude
i already found packetparser.kt that make radar not working thank alot

**Comment by arnanmaipradit** [comment]
that version still can't use after updated 13 March

**Comment by Jerry1211** [comment]
done
