### ISSUE TITLE
Where is the discord now?

### ISSUE THREAD

**Issue by pubgrad** [Jerry1211/Radar#5]
Discord channel just disappeared. Whats going on?

**Comment by Th3C0D3R** [comment]
lul restart Discord and or PC 😉

**Comment by pubgrad** [comment]
plz send me discord invite link.

**Comment by pubgrad** [comment]
IT says invalid link. Tried on two different discord accounts and devices

**Comment by Jerry1211** [comment]
https://discord.gg/96dzQDH

**Comment by pubgrad** [comment]
Again invalid or expired error.

**Comment by pubgrad** [comment]
Anonymous#2577

plz invite. thanks

**Comment by whitewingz2017** [comment]
https://discord.gg/vN7rDAJ

**Comment by pubgrad** [comment]
@whitewingz2017 Still invalid or expired link. Tried with two accounts same

**Comment by Jerry1211** [comment]
https://discord.gg/96dzQDH

**Comment by pubgrad** [comment]
same error

**Comment by xXSkrill1337** [comment]
https://discord.gg/MGtEyZ5

**Comment by pubgrad** [comment]
wth again invalid or expired invite

**Comment by pubgrad** [comment]
nvm seems like my country is blocked. Used vpn and link worked
